Fix the script responsible to update Nagios configuration
Nagios re-configuration relied on the existence of the file
/etc/hiera/nodes.yaml but this file is not more present.

The script relies now on both files astute.yaml and deleted_nodes.yaml.

Closes-bug: #1596830

Change-Id: I3ab8ac72d098b43c009a4fc8a7dfb72fab9ca5d4

diff --git a/deployment_scripts/puppet/modules/lma_infra_alerting/files/update-lma-configuration b/deployment_scripts/puppet/modules/lma_infra_alerting/files/update-lma-configuration
--- a/deployment_scripts/puppet/modules/lma_infra_alerting/files/update-lma-configuration
+++ b/deployment_scripts/puppet/modules/lma_infra_alerting/files/update-lma-configuration
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-set -e
-
 PLUGIN_NAME=$1
 
 MANIFEST=nagios.pp
@@ -11,47 +9,57 @@ EXTENSION_FILENAMES=.cfg
 PUPPET=$(which puppet)
 PLUGIN_PUPPET_DIR=$(ls -d /etc/fuel/plugins/"$PLUGIN_NAME"*/puppet)
 LAST_CHECK=/var/cache/lma_last_nodes_yaml.md5sum
+LAST_CHECK_DELETED=/var/cache/lma_last_deleted_nodes_yaml.md5sum
 CURRENT_CHECK=/var/cache/lma_current_nodes_yaml.md5sum
-NODES=/etc/hiera/nodes.yaml
+CURRENT_CHECK_DELETED=/var/cache/lma_current_deleted_nodes_yaml.md5sum
+ASTUTE=/etc/hiera/astute.yaml
+DELETED=/etc/hiera/deleted_nodes.yaml
 
 if [[ -z "$PLUGIN_NAME" ]]; then
   cat << EOT
   Usage: $0 <PLUGIN_NAME>
 
-  If $NODES has changed since the last run, re-apply nagios manifest.
-  Before puppet apply, the script removes purge nagios configuration files.
+  If $ASTUTE or $DELETED have changed since the last run, re-apply nagios manifest.
+  Before puppet apply, the script removes the StackLight nagios configuration files.
 EOT
   exit 1
 fi
 
-if [ ! -f "$NODES" ]; then
-    echo "missing $NODES file!"
+if [[ ! -f "$ASTUTE"  || ! -f "$DELETED" ]]; then
+    echo "missing one or both files $ASTUTE and/or $DELETED !"
     exit 1
 fi
 
-if [ ! -f $LAST_CHECK ]; then
+if [[ ! -f $LAST_CHECK || ! -f $DELETED ]]; then
     # First run
-    md5sum $NODES 2>/dev/null > $LAST_CHECK
+    md5sum $ASTUTE 2>/dev/null > $LAST_CHECK
+    md5sum $DELETED 2>/dev/null > $LAST_CHECK_DELETED
     exit 0
 fi
 
-md5sum $NODES > $CURRENT_CHECK
-set +e
-md5sum --status -c $LAST_CHECK
-result=$?
-set -e
+md5sum $ASTUTE > $CURRENT_CHECK
+md5sum $DELETED > $CURRENT_CHECK_DELETED
 
-if [ $result -eq 1 ]; then
+md5sum --status -c $LAST_CHECK
+result_astute=$?
+md5sum --status -c $LAST_CHECK_DELETED
+result_deleted=$?
+
+if [[ $result_astute -ne 0 || $result_deleted -ne 0 ]]; then
   if [ -d "$CONFIG_DIR" ]; then
     rm -f "$CONFIG_DIR"/"$PREFIX_FILENAMES"*"$EXTENSION_FILENAMES"
   fi
+  set -e
   $PUPPET apply --modulepath="$PLUGIN_PUPPET_DIR/modules/:/etc/puppet/modules" "$PLUGIN_PUPPET_DIR/manifests/$MANIFEST"
   set +e
-  md5sum --status -c $CURRENT_CHECK
-  result=$?
-  set -e
-  if [ $result -ne 1 ]; then
-    # OK, the $NODES file hasn't been modified during the puppet run
-    md5sum $NODES > $LAST_CHECK
+
+  md5sum --status  -c $LAST_CHECK
+  result_astute=$?
+  md5sum --status  -c $LAST_CHECK_DELETED
+  result_deleted=$?
+  if [[ $result_astute -ne 0 || $result_deleted -ne 0 ]]; then
+    # OK, the hiera data hasn't been modified during the puppet run
+    md5sum $ASTUTE > $LAST_CHECK
+    md5sum $DELETED > $LAST_CHECK_DELETED
   fi
 fi
